name: kids_learning_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  confetti: ^0.8.0
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/bear.png
    - assets/success.mp3
    - assets/out.mp3
    - assets/kids_bg.png
    - assets/happy.gif
    - assets/story1.png
